# Generated by Django 5.2.6 on 2025-09-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoreo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoreo.zone'),
        ),
    ]
